# Generated by Django 5.1.1 on 2024-09-25 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negozio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('recensione_media', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scontrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('negozio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scontrini.negozio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaProdotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scontrini.prodotto')),
                ('scontrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='scontrini.scontrino')),
            ],
        ),
    ]
