# Generated by Django 5.1.1 on 2024-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scontrini', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaprodotti',
            options={'verbose_name_plural': 'ListaProdotti'},
        ),
        migrations.AlterModelOptions(
            name='negozio',
            options={'verbose_name_plural': 'Negozi'},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AlterModelOptions(
            name='scontrino',
            options={'verbose_name_plural': 'Scontrini'},
        ),
        migrations.AddField(
            model_name='scontrino',
            name='totale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
