# Generated by Django 5.1.2 on 2024-11-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scontrini', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.AddField(
            model_name='prodotto',
            name='categoria_confermata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scontrini.categoria'),
        ),
        migrations.CreateModel(
            name='ProdottoConosciuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_specifico', models.CharField(max_length=100, unique=True)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scontrini.categoria')),
            ],
            options={
                'verbose_name_plural': 'ProdottiConosciuti',
            },
        ),
    ]
