# Generated by Django 5.1.2 on 2024-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scontrini', '0005_categoria_prodotto_categoria_confermata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scontrino',
            name='mostra_categoria',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ProdottoConosciuto',
        ),
    ]
