# Generated by Django 5.1.1 on 2024-09-25 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scontrini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField()),
                ('commento', models.TextField(null=True)),
                ('negozio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='scontrini.negozio')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scontrini.negozio')),
            ],
        ),
    ]
